// Array de tiendas de juegos con su ID, nombre y banner
const storesArray = [
  { storeID: "1", storeName: "Steam", banner: "0.png" },
  { storeID: "2", storeName: "GamersGate", banner: "1.png" },
  { storeID: "3", storeName: "GreenManGaming", banner: "2.png" },
  { storeID: "4", storeName: "Amazon", banner: "3.png" },
  { storeID: "5", storeName: "GameStop", banner: "4.png" },
  { storeID: "6", storeName: "Direct2Drive", banner: "5.png" },
  { storeID: "7", storeName: "GOG", banner: "6.png" },
  { storeID: "8", storeName: "Origin", banner: "7.png" },
  { storeID: "9", storeName: "Get Games", banner: "8.png" },
  { storeID: "10", storeName: "Shiny Loot", banner: "9.png" },
  { storeID: "11", storeName: "Humble Store", banner: "10.png" },
  { storeID: "12", storeName: "Desura", banner: "11.png" },
  { storeID: "13", storeName: "Uplay", banner: "12.png" },
  { storeID: "14", storeName: "IndieGameStand", banner: "13.png" },
  { storeID: "15", storeName: "Fanatical", banner: "14.png" },
  { storeID: "16", storeName: "Gamesrocket", banner: "15.png" },
  { storeID: "17", storeName: "Games Republic", banner: "16.png" },
  { storeID: "18", storeName: "SilaGames", banner: "17.png" },
  { storeID: "19", storeName: "Playfield", banner: "18.png" },
  { storeID: "20", storeName: "ImperialGames", banner: "19.png" },
  { storeID: "21", storeName: "WinGameStore", banner: "20.png" },
  { storeID: "22", storeName: "FunStockDigital", banner: "21.png" },
  { storeID: "23", storeName: "GameBillet", banner: "22.png" },
  { storeID: "24", storeName: "Voidu", banner: "23.png" },
  { storeID: "25", storeName: "Epic Games Store", banner: "24.png" },
  { storeID: "26", storeName: "Razer Game Store", banner: "25.png" },
  { storeID: "27", storeName: "Gamesplanet", banner: "26.png" },
  { storeID: "28", storeName: "Gamesload", banner: "27.png" },
  { storeID: "29", storeName: "2Game", banner: "28.png" },
  { storeID: "30", storeName: "IndieGala", banner: "29.png" },
  { storeID: "31", storeName: "Blizzard Shop", banner: "30.png" },
  { storeID: "32", storeName: "AllYouPlay", banner: "31.png" },
  { storeID: "33", storeName: "DLGamer", banner: "32.png" },
  { storeID: "34", storeName: "Noctre", banner: "33.png" },
  { storeID: "35", storeName: "DreamGame", banner: "34.png" },
];

// Exporta el array de tiendas para que pueda ser utilizado en otros archivos
module.exports = storesArray;
